const DRAFT_KEY='maximos-catalog-draft-v2';let catalog={updatedAt:new Date().toISOString().slice(0,10),currency:'BRL',products:[]};let selectedId=null;let pendingDelete=null;
const list=document.querySelector('[data-list]'),editor=document.querySelector('[data-editor]'),template=document.querySelector('#editor-template'),confirmDialog=document.querySelector('[data-confirm]');
const cleanLines=value=>value.split('\n').map(item=>item.trim()).filter(Boolean);const slugify=value=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function store(){catalog.updatedAt=new Date().toISOString().slice(0,10);localStorage.setItem(DRAFT_KEY,JSON.stringify(catalog))}
function renderList(query=''){const term=query.toLowerCase();const visible=[...catalog.products].sort((a,b)=>a.ordem-b.ordem).filter(p=>`${p.nome} ${p.colecao}`.toLowerCase().includes(term));document.querySelector('[data-total]').textContent=catalog.products.length;list.innerHTML=visible.map(p=>`<button type="button" data-id="${p.id}" class="${p.id===selectedId?'active':''}"><img src="${p.imagens?.[0]||'assets/hero-conceitual.png'}" alt=""><span><b>${p.nome}</b><small>${p.colecao||'Sem coleção'}</small></span><i class="availability-dot ${p.disponivel?'':'no'}" title="${p.disponivel?'Disponível':'Indisponível'}"></i></button>`).join('')||'<p>Nenhum produto encontrado.</p>';list.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>selectProduct(button.dataset.id)))}
function selectProduct(id){selectedId=id;renderList(document.querySelector('[data-search]').value);renderEditor()}
function renderEditor(){const product=catalog.products.find(p=>p.id===selectedId);if(!product){editor.innerHTML='<div class="empty-editor"><span>MS</span><h1>Selecione uma peça</h1><p>Escolha um produto na lista ou adicione um novo.</p></div>';return}editor.innerHTML='';editor.append(template.content.cloneNode(true));const form=editor.querySelector('[data-form]');editor.querySelector('[data-title]').textContent=product.nome;editor.querySelector('[data-position]').textContent=`Produto ${product.ordem} de ${catalog.products.length}`;const values={...product,materiais:(product.materiais||[]).join('\n'),cores:(product.cores||[]).join('\n'),imagens:(product.imagens||[]).join('\n'),largura:product.medidas?.largura??'',altura:product.medidas?.altura??'',profundidade:product.medidas?.profundidade??''};Object.entries(values).forEach(([name,value])=>{const field=form.elements[name];if(!field)return;if(field.type==='checkbox')field.checked=Boolean(value);else field.value=value??''});updatePreview();form.elements.imagens.addEventListener('input',updatePreview);form.elements.nome.addEventListener('input',()=>{if(!form.elements.id.dataset.touched)form.elements.id.value=slugify(form.elements.nome.value)});form.elements.id.addEventListener('input',()=>form.elements.id.dataset.touched='true');form.addEventListener('submit',saveForm);editor.querySelector('[data-duplicate]').addEventListener('click',duplicateProduct);editor.querySelector('[data-delete]').addEventListener('click',()=>{pendingDelete=product.id;confirmDialog.showModal()})}
function updatePreview(){const form=editor.querySelector('[data-form]');if(!form)return;const src=cleanLines(form.elements.imagens.value)[0];const image=editor.querySelector('[data-image-preview]'),empty=editor.querySelector('[data-no-image]');if(src){image.src=src;image.hidden=false;empty.hidden=true;image.onerror=()=>{image.hidden=true;empty.hidden=false}}else{image.hidden=true;empty.hidden=false}}
function saveForm(event){event.preventDefault();const form=event.currentTarget;const existingIndex=catalog.products.findIndex(p=>p.id===selectedId);const existing=catalog.products[existingIndex]||{};const data=new FormData(form);const dims=['largura','altura','profundidade'].map(key=>Number(data.get(key))||null);const product={...existing,id:String(data.get('id')).trim(),nome:String(data.get('nome')).trim(),categoria:String(data.get('categoria')).trim(),colecao:String(data.get('colecao')).trim(),preco:Number(data.get('preco')),precoAnterior:Number(data.get('precoAnterior'))||null,disponivel:form.elements.disponivel.checked,destaque:form.elements.destaque.checked,resumo:String(data.get('resumo')).trim(),descricao:String(data.get('descricao')).trim(),materiais:cleanLines(String(data.get('materiais'))),cores:cleanLines(String(data.get('cores'))),medidas:dims.some(Boolean)?{largura:dims[0],altura:dims[1],profundidade:dims[2]}:null,imagens:cleanLines(String(data.get('imagens'))),imagemConceitual:form.elements.imagemConceitual.checked,ordem:Number(data.get('ordem'))||catalog.products.length};if(catalog.products.some((p,index)=>p.id===product.id&&index!==existingIndex)){alert('Já existe outro produto com este ID.');return}catalog.products[existingIndex]=product;selectedId=product.id;store();renderList(document.querySelector('[data-search]').value);renderEditor();const status=editor.querySelector('[data-status]');status.textContent='Alterações salvas no rascunho.';setTimeout(()=>status.textContent='Alterações salvas como rascunho neste navegador.',1800)}
function addProduct(){const next=catalog.products.length+1;const product={id:`nova-peca-${next}`,nome:'Nova peça',categoria:'Bolsas',colecao:'',preco:0,precoAnterior:null,disponivel:true,destaque:false,resumo:'',descricao:'',materiais:['Couro legítimo'],cores:['Consultar disponibilidade'],medidas:null,imagens:['assets/hero-conceitual.png'],imagemConceitual:true,ordem:next};catalog.products.push(product);selectedId=product.id;store();renderList();renderEditor()}
function duplicateProduct(){const source=catalog.products.find(p=>p.id===selectedId);const copy=structuredClone(source);copy.id=`${source.id}-copia`;copy.nome=`${source.nome} — cópia`;copy.ordem=catalog.products.length+1;catalog.products.push(copy);selectedId=copy.id;store();renderList();renderEditor()}
function deleteProduct(){catalog.products=catalog.products.filter(p=>p.id!==pendingDelete);selectedId=catalog.products[0]?.id||null;pendingDelete=null;store();confirmDialog.close();renderList();renderEditor()}
function exportCatalog(){store();const blob=new Blob([JSON.stringify(catalog,null,2)+'\n'],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='products.json';link.click();URL.revokeObjectURL(url)}
function importCatalog(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.products))throw new Error();catalog=data;selectedId=catalog.products[0]?.id||null;store();renderList();renderEditor()}catch{alert('O arquivo não possui um catálogo válido.')}};reader.readAsText(file)}
document.querySelector('[data-add]').addEventListener('click',addProduct);document.querySelector('[data-search]').addEventListener('input',event=>renderList(event.target.value));document.querySelector('[data-export]').addEventListener('click',exportCatalog);document.querySelector('[data-import]').addEventListener('change',event=>event.target.files[0]&&importCatalog(event.target.files[0]));document.querySelector('[data-cancel]').addEventListener('click',()=>confirmDialog.close());document.querySelector('[data-confirm-delete]').addEventListener('click',deleteProduct);
const draft=localStorage.getItem(DRAFT_KEY);(draft?Promise.resolve(JSON.parse(draft)):fetch('data/products.json').then(response=>response.json())).then(data=>{catalog=data;selectedId=catalog.products[0]?.id||null;renderList();renderEditor()}).catch(()=>{renderList()});
