const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});let products=[];let activeFilter='todos';const activeMessage='Olá! Gostaria de conhecer melhor as peças da Maximos Signature.';const header=document.querySelector('[data-header]'),menu=document.querySelector('.menu-toggle'),dialog=document.querySelector('[data-dialog]');
const escapeHtml=value=>String(value??'').replace(/[&<>\"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[char]));
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24),{passive:true});menu?.addEventListener('click',()=>{const open=header.classList.toggle('menu-open');menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Fechar':'Menu'});
function productCard(product,index){const old=product.precoAnterior?`<del>${money.format(product.precoAnterior)}</del>`:'';return `<article class="catalog-item reveal"><a class="catalog-card" href="produto.html?id=${encodeURIComponent(product.id)}" aria-label="Conhecer ${escapeHtml(product.nome)}"><div class="catalog-image"><img src="${escapeHtml(product.imagens[0])}" alt="${escapeHtml(product.nome)}" loading="lazy"><span class="catalog-status ${product.disponivel?'':'unavailable'}">${product.disponivel?'Disponível':'Sob consulta'}</span><span class="catalog-number">${String(index+1).padStart(2,'0')}</span></div><div class="catalog-content"><div class="catalog-kicker"><span>${escapeHtml(product.colecao)}</span><span>${escapeHtml(product.categoria)}</span></div><h2>${escapeHtml(product.nome)}</h2><p class="catalog-summary">${escapeHtml(product.resumo)}</p><div class="catalog-bottom"><span class="catalog-price"><strong>${money.format(product.preco)}</strong>${old}</span><span class="catalog-open">Descobrir →</span></div></div></a></article>`}
function reveal(){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
function render(){const visible=products.filter(p=>activeFilter==='disponiveis'?p.disponivel:activeFilter==='destaques'?p.destaque:true);document.querySelector('[data-count]').textContent=visible.length;const grid=document.querySelector('[data-catalog]');grid.innerHTML=visible.map(productCard).join('')||'<p class="catalog-loading">Nenhuma peça nesta seleção.</p>';grid.setAttribute('aria-busy','false');reveal()}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.classList.remove('is-active'));button.classList.add('is-active');activeFilter=button.dataset.filter;render();document.querySelector('.catalog-grid').scrollIntoView({behavior:'smooth',block:'start'})}));
function contact(event){event?.preventDefault();const number=window.SITE_CONFIG?.whatsapp;if(number){location.href=`https://wa.me/${number}?text=${encodeURIComponent(activeMessage)}`;return}document.querySelector('[data-message]').textContent=activeMessage;dialog.showModal()}
document.querySelectorAll('[data-contact]').forEach(link=>link.addEventListener('click',contact));document.querySelector('[data-close]')?.addEventListener('click',()=>dialog.close());document.querySelector('[data-copy]')?.addEventListener('click',async event=>{await navigator.clipboard.writeText(activeMessage);event.currentTarget.textContent='Mensagem copiada'});
fetch('data/products.json').then(response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>{products=data.products.sort((a,b)=>a.ordem-b.ordem);render()}).catch(()=>{document.querySelector('[data-catalog]').innerHTML='<p class="catalog-loading">Não foi possível carregar a coleção.</p>'});document.querySelector('[data-year]').textContent=new Date().getFullYear();
